version: '3.4'

services:
  server:
    image: nnhathung97/eventyay-video:testing-server
    ports:
      - "8375:8375"
    volumes:
      #- ./server:/app
      - appdata:/data
    environment:
        - VENUELESS_DB_TYPE=postgresql
        - VENUELESS_DB_NAME=venueless
        - VENUELESS_DB_USER=venueless
        - VENUELESS_DB_PASS=venueless
        - VENUELESS_DB_HOST=db
        - VENUELESS_REDIS_URLS=redis://redis:6379/0,redis://redis1:6379/0
        - VENUELESS_DATA_DIR=/data
        - VENUELESS_MEDIA_URL=http://localhost:8375/media/
        - VENUELESS_REDIS_USE_PUBSUB=true
    depends_on:
      - db
      - redis
      - redis1
    entrypoint: ["bash", "/app/docker-dev-entrypoint.sh"]

  celery:
    image: nnhathung97/eventyay-video:testing-server
    volumes:
      #- ./server:/app
      - appdata:/data
    environment:
        - VENUELESS_DB_TYPE=postgresql
        - VENUELESS_DB_NAME=venueless
        - VENUELESS_DB_USER=venueless
        - VENUELESS_DB_PASS=venueless
        - VENUELESS_DB_HOST=db
        - VENUELESS_REDIS_URLS=redis://redis:6379/0,redis://redis1:6379/0
        - VENUELESS_DATA_DIR=/data
        - VENUELESS_MEDIA_URL=http://localhost:8375/media/
    depends_on:
      - db
      - redis
      - redis1
    entrypoint: ["bash", "/app/docker-dev-entrypoint-celery.sh"]

  webapp:
    image: nnhathung97/eventyay-video:testing-webapp
    ports:
      - "8880:8880"
    #volumes:
      #- ./webapp:/app
    command: npm start -- --host 0.0.0.0

  redis:
    image: redis:latest
    container_name: redis

  redis1:
    image: redis:latest
    container_name: redis1

  db:
    image: postgres:15
    container_name: db
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_INITDB_ARGS=--auth-host=md5
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_USER=venueless
      - POSTGRES_PASSWORD=venueless

volumes:
  postgres_data:
  appdata:

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.178.0.0/16