name: Main workflow
on:
  push:
    branches:
      - feature-94
  workflow_dispatch:
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push server Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./server
        file: ./server/Dockerfile-dev
        push: true
        tags: odkhang/eventyay-video:development-server

    - name: Build and push webapp Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./webapp
        file: ./webapp/Dockerfile-dev
        push: true
        tags: odkhang/eventyay-video:development-webapp

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: odkhang/eventyay-video:development-latest
        
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Deploy
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        eval "$(ssh-agent -s)"
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        scp docker-compose.yml "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/eventyay/eventyay-videos"
        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "cd /home/eventyay/eventyay-videos && sudo docker pull odkhang/eventyay-video:development-server && sudo docker pull odkhang/eventyay-video:development-webapp && sudo docker pull odkhang/eventyay-video:development-latest && sudo docker-compose up -d"